# Generated by Django 5.0.6 on 2024-05-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.TextField(max_length=1000)),
                ("image", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="dish",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
