# Generated by Django 5.0.6 on 2024-05-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_dish_recipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="recipe",
        ),
        migrations.AddField(
            model_name="dish",
            name="recipe",
            field=models.ManyToManyField(related_name="dishes", to="catalog.step"),
        ),
    ]
