# Generated by Django 5.0.6 on 2024-05-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_dish_recipe_dish_recipe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="review",
            name="dish",
        ),
        migrations.AddField(
            model_name="review",
            name="dish",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="catalog.dish",
            ),
            preserve_default=False,
        ),
    ]
