# Generated by Django 5.0.6 on 2024-05-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_cook_options_category_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.URLField(
                blank=True,
                default="https://img.freepik.com/free-psd/breakfast-item-icon-isolated-3d-render-ilustration_47987-11153.jpg?size=338&ext=jpg&ga=GA1.1.1292351815.1709337600&semt=ais",
                null=True,
            ),
        ),
    ]
