# Generated by Django 4.2.13 on 2024-05-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_category_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dish",
            name="recipe",
        ),
        migrations.DeleteModel(
            name="Step",
        ),
        migrations.AddField(
            model_name="dish",
            name="recipe",
            field=models.TextField(default="Some very simple recipe", max_length=10000),
            preserve_default=False,
        ),
    ]
