# Generated by Django 4.2.13 on 2024-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_remove_dish_recipe_delete_step_dish_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
