# Generated by Django 4.2.13 on 2024-05-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_cook_add_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cook",
            name="add_date",
        ),
    ]
