# Generated by Django 4.2.13 on 2024-05-19 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_cook_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="cook",
            name="add_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
