# Generated by Django 4.2.13 on 2024-05-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_cook_add_date_alter_review_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={"ordering": ["-addition_date"], "verbose_name_plural": "Dishes"},
        ),
        migrations.RemoveField(
            model_name="cook",
            name="add_date",
        ),
        migrations.AlterField(
            model_name="review",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
